{% set version = "0.7.1" %}

package:
  name: rpds-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rpds-py/rpds_py-{{ version }}.tar.gz
  sha256: d940b5644f14e49b1c6e7902b9ec8a0c7584109fbf380fa18115831a641927c8

build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin >=0.14,<0.15
    - pip
    - python
  run:
    - python

test:
  imports:
    - rpds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/julian/rpds.py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
