# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.26.0"
  maturin_min: "1.2"
  maturin_max: "2.0"

package:
  name: rpds-py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rpds-py/rpds_py-${{ version }}.tar.gz
  sha256: 20dae58a859b0906f0685642e591056f1e787f3a8b39c8e8749a45dc7d26bdb0

build:
  number: 0
  script:
    file: build-rpds-py

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
        - python
  host:
    - maturin >=${{ maturin_min }},<${{ maturin_max }}
    - pip
    - python
  run:
    - python

tests:
  - python:
      pip_check: true
      imports: rpds
  - files:
      source:
        - tests/
    requirements:
      run:
        - coverage
        - pytest
    script:
      - coverage run --source=rpds --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=83

about:
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/crate-py/rpds
  documentation: https://rpds.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
