azure:
  free_disk_space: true
bot:
  inspection: hint-all
build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
